# coding: utf-8

"""
    KFServing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_root_paths import IoK8sApimachineryPkgApisMetaV1RootPaths  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1RootPaths(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1RootPaths unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1RootPaths(self):
        """Test IoK8sApimachineryPkgApisMetaV1RootPaths"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_root_paths.IoK8sApimachineryPkgApisMetaV1RootPaths()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
