# coding: utf-8

"""
    KFServing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_apimachinery_pkg_runtime_unknown import IoK8sApimachineryPkgRuntimeUnknown  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApimachineryPkgRuntimeUnknown(unittest.TestCase):
    """IoK8sApimachineryPkgRuntimeUnknown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgRuntimeUnknown(self):
        """Test IoK8sApimachineryPkgRuntimeUnknown"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_apimachinery_pkg_runtime_unknown.IoK8sApimachineryPkgRuntimeUnknown()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
