# coding: utf-8

"""
    KFServing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_github_kubeflow_kfserving_pkg_apis_serving_v1alpha1_kf_service_list import ComGithubKubeflowKfservingPkgApisServingV1alpha1KFServiceList  # noqa: E501
from swagger_client.rest import ApiException


class TestComGithubKubeflowKfservingPkgApisServingV1alpha1KFServiceList(unittest.TestCase):
    """ComGithubKubeflowKfservingPkgApisServingV1alpha1KFServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComGithubKubeflowKfservingPkgApisServingV1alpha1KFServiceList(self):
        """Test ComGithubKubeflowKfservingPkgApisServingV1alpha1KFServiceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_github_kubeflow_kfserving_pkg_apis_serving_v1alpha1_kf_service_list.ComGithubKubeflowKfservingPkgApisServingV1alpha1KFServiceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
