# coding: utf-8

"""
    KFServing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.com_github_kubeflow_kfserving_pkg_apis_serving_v1alpha1_condition import ComGithubKubeflowKfservingPkgApisServingV1alpha1Condition  # noqa: F401,E501


class ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conditions': 'list[ComGithubKubeflowKfservingPkgApisServingV1alpha1Condition]'
    }

    attribute_map = {
        'conditions': 'conditions'
    }

    def __init__(self, conditions=None):  # noqa: E501
        """ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec - a model defined in Swagger"""  # noqa: E501

        self._conditions = None
        self.discriminator = None

        if conditions is not None:
            self.conditions = conditions

    @property
    def conditions(self):
        """Gets the conditions of this ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec.  # noqa: E501

        Conditions the latest available observations of a resource's current state.  # noqa: E501

        :return: The conditions of this ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec.  # noqa: E501
        :rtype: list[ComGithubKubeflowKfservingPkgApisServingV1alpha1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec.

        Conditions the latest available observations of a resource's current state.  # noqa: E501

        :param conditions: The conditions of this ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec.  # noqa: E501
        :type: list[ComGithubKubeflowKfservingPkgApisServingV1alpha1Condition]
        """

        self._conditions = conditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubKubeflowKfservingPkgApisServingV1alpha1StatusConditionsSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
