# coding: utf-8

"""
    KFServing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.com_github_kubeflow_kfserving_pkg_apis_serving_v1alpha1_framework_config import ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig  # noqa: F401,E501


class ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sklearn': 'ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig',
        'tensorflow': 'ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig',
        'xgboost': 'ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig'
    }

    attribute_map = {
        'sklearn': 'sklearn',
        'tensorflow': 'tensorflow',
        'xgboost': 'xgboost'
    }

    def __init__(self, sklearn=None, tensorflow=None, xgboost=None):  # noqa: E501
        """ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig - a model defined in Swagger"""  # noqa: E501

        self._sklearn = None
        self._tensorflow = None
        self._xgboost = None
        self.discriminator = None

        if sklearn is not None:
            self.sklearn = sklearn
        if tensorflow is not None:
            self.tensorflow = tensorflow
        if xgboost is not None:
            self.xgboost = xgboost

    @property
    def sklearn(self):
        """Gets the sklearn of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501


        :return: The sklearn of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501
        :rtype: ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig
        """
        return self._sklearn

    @sklearn.setter
    def sklearn(self, sklearn):
        """Sets the sklearn of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.


        :param sklearn: The sklearn of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501
        :type: ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig
        """

        self._sklearn = sklearn

    @property
    def tensorflow(self):
        """Gets the tensorflow of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501


        :return: The tensorflow of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501
        :rtype: ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig
        """
        return self._tensorflow

    @tensorflow.setter
    def tensorflow(self, tensorflow):
        """Sets the tensorflow of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.


        :param tensorflow: The tensorflow of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501
        :type: ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig
        """

        self._tensorflow = tensorflow

    @property
    def xgboost(self):
        """Gets the xgboost of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501


        :return: The xgboost of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501
        :rtype: ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig
        """
        return self._xgboost

    @xgboost.setter
    def xgboost(self, xgboost):
        """Sets the xgboost of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.


        :param xgboost: The xgboost of this ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig.  # noqa: E501
        :type: ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworkConfig
        """

        self._xgboost = xgboost

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
